/*
 * generated by Xtext 2.30.0
 */
package org.xtext.poglanguage.pogl.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractPogLScopeProvider extends DelegatingScopeProvider {
}
