/**
 * generated by Xtext 2.30.0
 */
package org.xtext.poglanguage.pogl.pogL;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Action</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.poglanguage.pogl.pogL.Action#getState_name <em>State name</em>}</li>
 *   <li>{@link org.xtext.poglanguage.pogl.pogL.Action#getDescription <em>Description</em>}</li>
 *   <li>{@link org.xtext.poglanguage.pogl.pogL.Action#getOperations <em>Operations</em>}</li>
 * </ul>
 *
 * @see org.xtext.poglanguage.pogl.pogL.PogLPackage#getAction()
 * @model
 * @generated
 */
public interface Action extends Operation
{
  /**
   * Returns the value of the '<em><b>State name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>State name</em>' attribute.
   * @see #setState_name(String)
   * @see org.xtext.poglanguage.pogl.pogL.PogLPackage#getAction_State_name()
   * @model
   * @generated
   */
  String getState_name();

  /**
   * Sets the value of the '{@link org.xtext.poglanguage.pogl.pogL.Action#getState_name <em>State name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>State name</em>' attribute.
   * @see #getState_name()
   * @generated
   */
  void setState_name(String value);

  /**
   * Returns the value of the '<em><b>Description</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Description</em>' attribute.
   * @see #setDescription(String)
   * @see org.xtext.poglanguage.pogl.pogL.PogLPackage#getAction_Description()
   * @model
   * @generated
   */
  String getDescription();

  /**
   * Sets the value of the '{@link org.xtext.poglanguage.pogl.pogL.Action#getDescription <em>Description</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Description</em>' attribute.
   * @see #getDescription()
   * @generated
   */
  void setDescription(String value);

  /**
   * Returns the value of the '<em><b>Operations</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Operations</em>' containment reference.
   * @see #setOperations(Operations)
   * @see org.xtext.poglanguage.pogl.pogL.PogLPackage#getAction_Operations()
   * @model containment="true"
   * @generated
   */
  Operations getOperations();

  /**
   * Sets the value of the '{@link org.xtext.poglanguage.pogl.pogL.Action#getOperations <em>Operations</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Operations</em>' containment reference.
   * @see #getOperations()
   * @generated
   */
  void setOperations(Operations value);

} // Action
