/**
 * generated by Xtext 2.30.0
 */
package org.xtext.poglanguage.pogl.pogL;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>FCheck</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.poglanguage.pogl.pogL.FCheck#getItem <em>Item</em>}</li>
 *   <li>{@link org.xtext.poglanguage.pogl.pogL.FCheck#getFCheck_item <em>FCheck item</em>}</li>
 * </ul>
 *
 * @see org.xtext.poglanguage.pogl.pogL.PogLPackage#getFCheck()
 * @model
 * @generated
 */
public interface FCheck extends EObject
{
  /**
   * Returns the value of the '<em><b>Item</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Item</em>' reference.
   * @see #setItem(Fitem)
   * @see org.xtext.poglanguage.pogl.pogL.PogLPackage#getFCheck_Item()
   * @model
   * @generated
   */
  Fitem getItem();

  /**
   * Sets the value of the '{@link org.xtext.poglanguage.pogl.pogL.FCheck#getItem <em>Item</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Item</em>' reference.
   * @see #getItem()
   * @generated
   */
  void setItem(Fitem value);

  /**
   * Returns the value of the '<em><b>FCheck item</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>FCheck item</em>' containment reference.
   * @see #setFCheck_item(FCheck_item)
   * @see org.xtext.poglanguage.pogl.pogL.PogLPackage#getFCheck_FCheck_item()
   * @model containment="true"
   * @generated
   */
  FCheck_item getFCheck_item();

  /**
   * Sets the value of the '{@link org.xtext.poglanguage.pogl.pogL.FCheck#getFCheck_item <em>FCheck item</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>FCheck item</em>' containment reference.
   * @see #getFCheck_item()
   * @generated
   */
  void setFCheck_item(FCheck_item value);

} // FCheck
