/**
 * generated by Xtext 2.30.0
 */
package org.xtext.poglanguage.pogl.pogL;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>FComparison Operators</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.poglanguage.pogl.pogL.PogLPackage#getFComparison_Operators()
 * @model
 * @generated
 */
public interface FComparison_Operators extends EObject
{
} // FComparison_Operators
