/**
 * generated by Xtext 2.30.0
 */
package org.xtext.poglanguage.pogl.pogL;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>FINT</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.poglanguage.pogl.pogL.PogLPackage#getFINT()
 * @model
 * @generated
 */
public interface FINT extends FComparison_Operators
{
} // FINT
