/**
 * generated by Xtext 2.30.0
 */
package org.xtext.poglanguage.pogl.pogL;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>FOperations</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.poglanguage.pogl.pogL.FOperations#getOperations <em>Operations</em>}</li>
 * </ul>
 *
 * @see org.xtext.poglanguage.pogl.pogL.PogLPackage#getFOperations()
 * @model
 * @generated
 */
public interface FOperations extends EObject
{
  /**
   * Returns the value of the '<em><b>Operations</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Operations</em>' containment reference.
   * @see #setOperations(Operations)
   * @see org.xtext.poglanguage.pogl.pogL.PogLPackage#getFOperations_Operations()
   * @model containment="true"
   * @generated
   */
  Operations getOperations();

  /**
   * Sets the value of the '{@link org.xtext.poglanguage.pogl.pogL.FOperations#getOperations <em>Operations</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Operations</em>' containment reference.
   * @see #getOperations()
   * @generated
   */
  void setOperations(Operations value);

} // FOperations
