/**
 * generated by Xtext 2.30.0
 */
package org.xtext.poglanguage.pogl.pogL;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Fstate name</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.poglanguage.pogl.pogL.Fstate_name#getDescription <em>Description</em>}</li>
 * </ul>
 *
 * @see org.xtext.poglanguage.pogl.pogL.PogLPackage#getFstate_name()
 * @model
 * @generated
 */
public interface Fstate_name extends EObject
{
  /**
   * Returns the value of the '<em><b>Description</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Description</em>' attribute.
   * @see #setDescription(String)
   * @see org.xtext.poglanguage.pogl.pogL.PogLPackage#getFstate_name_Description()
   * @model
   * @generated
   */
  String getDescription();

  /**
   * Sets the value of the '{@link org.xtext.poglanguage.pogl.pogL.Fstate_name#getDescription <em>Description</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Description</em>' attribute.
   * @see #getDescription()
   * @generated
   */
  void setDescription(String value);

} // Fstate_name
