/**
 * generated by Xtext 2.30.0
 */
package org.xtext.poglanguage.pogl.pogL;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Fstate</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.poglanguage.pogl.pogL.Fstate#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.poglanguage.pogl.pogL.Fstate#getFstate_name <em>Fstate name</em>}</li>
 * </ul>
 *
 * @see org.xtext.poglanguage.pogl.pogL.PogLPackage#getFstate()
 * @model
 * @generated
 */
public interface Fstate extends State
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.xtext.poglanguage.pogl.pogL.PogLPackage#getFstate_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.xtext.poglanguage.pogl.pogL.Fstate#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Fstate name</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Fstate name</em>' containment reference.
   * @see #setFstate_name(Fstate_name)
   * @see org.xtext.poglanguage.pogl.pogL.PogLPackage#getFstate_Fstate_name()
   * @model containment="true"
   * @generated
   */
  Fstate_name getFstate_name();

  /**
   * Sets the value of the '{@link org.xtext.poglanguage.pogl.pogL.Fstate#getFstate_name <em>Fstate name</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Fstate name</em>' containment reference.
   * @see #getFstate_name()
   * @generated
   */
  void setFstate_name(Fstate_name value);

} // Fstate
