/**
 * generated by Xtext 2.30.0
 */
package org.xtext.poglanguage.pogl.pogL;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>FThen Operations</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.poglanguage.pogl.pogL.FThenOperations#getOperationfalse <em>Operationfalse</em>}</li>
 * </ul>
 *
 * @see org.xtext.poglanguage.pogl.pogL.PogLPackage#getFThenOperations()
 * @model
 * @generated
 */
public interface FThenOperations extends EObject
{
  /**
   * Returns the value of the '<em><b>Operationfalse</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Operationfalse</em>' containment reference.
   * @see #setOperationfalse(Operations)
   * @see org.xtext.poglanguage.pogl.pogL.PogLPackage#getFThenOperations_Operationfalse()
   * @model containment="true"
   * @generated
   */
  Operations getOperationfalse();

  /**
   * Sets the value of the '{@link org.xtext.poglanguage.pogl.pogL.FThenOperations#getOperationfalse <em>Operationfalse</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Operationfalse</em>' containment reference.
   * @see #getOperationfalse()
   * @generated
   */
  void setOperationfalse(Operations value);

} // FThenOperations
