/**
 * generated by Xtext 2.30.0
 */
package org.xtext.poglanguage.pogl.pogL;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Goto</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.poglanguage.pogl.pogL.Goto#getState_name <em>State name</em>}</li>
 * </ul>
 *
 * @see org.xtext.poglanguage.pogl.pogL.PogLPackage#getGoto()
 * @model
 * @generated
 */
public interface Goto extends Operation
{
  /**
   * Returns the value of the '<em><b>State name</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>State name</em>' reference.
   * @see #setState_name(Fstate)
   * @see org.xtext.poglanguage.pogl.pogL.PogLPackage#getGoto_State_name()
   * @model
   * @generated
   */
  Fstate getState_name();

  /**
   * Sets the value of the '{@link org.xtext.poglanguage.pogl.pogL.Goto#getState_name <em>State name</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>State name</em>' reference.
   * @see #getState_name()
   * @generated
   */
  void setState_name(Fstate value);

} // Goto
