/**
 * generated by Xtext 2.30.0
 */
package org.xtext.poglanguage.pogl.pogL;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.poglanguage.pogl.pogL.PogLFactory
 * @model kind="package"
 * @generated
 */
public interface PogLPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "pogL";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/poglanguage/pogl/PogL";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "pogL";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  PogLPackage eINSTANCE = org.xtext.poglanguage.pogl.pogL.impl.PogLPackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.poglanguage.pogl.pogL.impl.ProgramImpl <em>Program</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.poglanguage.pogl.pogL.impl.ProgramImpl
   * @see org.xtext.poglanguage.pogl.pogL.impl.PogLPackageImpl#getProgram()
   * @generated
   */
  int PROGRAM = 0;

  /**
   * The feature id for the '<em><b>Models</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROGRAM__MODELS = 0;

  /**
   * The number of structural features of the '<em>Program</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROGRAM_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.poglanguage.pogl.pogL.impl.ModelImpl <em>Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.poglanguage.pogl.pogL.impl.ModelImpl
   * @see org.xtext.poglanguage.pogl.pogL.impl.PogLPackageImpl#getModel()
   * @generated
   */
  int MODEL = 1;

  /**
   * The feature id for the '<em><b>Model</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__MODEL = 0;

  /**
   * The number of structural features of the '<em>Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.poglanguage.pogl.pogL.impl.OperationImpl <em>Operation</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.poglanguage.pogl.pogL.impl.OperationImpl
   * @see org.xtext.poglanguage.pogl.pogL.impl.PogLPackageImpl#getOperation()
   * @generated
   */
  int OPERATION = 10;

  /**
   * The number of structural features of the '<em>Operation</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPERATION_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.xtext.poglanguage.pogl.pogL.impl.StateImpl <em>State</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.poglanguage.pogl.pogL.impl.StateImpl
   * @see org.xtext.poglanguage.pogl.pogL.impl.PogLPackageImpl#getState()
   * @generated
   */
  int STATE = 2;

  /**
   * The number of structural features of the '<em>State</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATE_FEATURE_COUNT = OPERATION_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.xtext.poglanguage.pogl.pogL.impl.FstateImpl <em>Fstate</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.poglanguage.pogl.pogL.impl.FstateImpl
   * @see org.xtext.poglanguage.pogl.pogL.impl.PogLPackageImpl#getFstate()
   * @generated
   */
  int FSTATE = 3;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FSTATE__NAME = STATE_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Fstate name</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FSTATE__FSTATE_NAME = STATE_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Fstate</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FSTATE_FEATURE_COUNT = STATE_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.poglanguage.pogl.pogL.impl.Fstate_nameImpl <em>Fstate name</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.poglanguage.pogl.pogL.impl.Fstate_nameImpl
   * @see org.xtext.poglanguage.pogl.pogL.impl.PogLPackageImpl#getFstate_name()
   * @generated
   */
  int FSTATE_NAME = 4;

  /**
   * The feature id for the '<em><b>Description</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FSTATE_NAME__DESCRIPTION = 0;

  /**
   * The number of structural features of the '<em>Fstate name</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FSTATE_NAME_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.poglanguage.pogl.pogL.impl.ItemImpl <em>Item</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.poglanguage.pogl.pogL.impl.ItemImpl
   * @see org.xtext.poglanguage.pogl.pogL.impl.PogLPackageImpl#getItem()
   * @generated
   */
  int ITEM = 5;

  /**
   * The number of structural features of the '<em>Item</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ITEM_FEATURE_COUNT = OPERATION_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.xtext.poglanguage.pogl.pogL.impl.FitemImpl <em>Fitem</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.poglanguage.pogl.pogL.impl.FitemImpl
   * @see org.xtext.poglanguage.pogl.pogL.impl.PogLPackageImpl#getFitem()
   * @generated
   */
  int FITEM = 6;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FITEM__NAME = ITEM_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Fitem name</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FITEM__FITEM_NAME = ITEM_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Fitem</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FITEM_FEATURE_COUNT = ITEM_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.poglanguage.pogl.pogL.impl.Fitem_nameImpl <em>Fitem name</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.poglanguage.pogl.pogL.impl.Fitem_nameImpl
   * @see org.xtext.poglanguage.pogl.pogL.impl.PogLPackageImpl#getFitem_name()
   * @generated
   */
  int FITEM_NAME = 7;

  /**
   * The feature id for the '<em><b>Amount</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FITEM_NAME__AMOUNT = 0;

  /**
   * The number of structural features of the '<em>Fitem name</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FITEM_NAME_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.poglanguage.pogl.pogL.impl.GotoImpl <em>Goto</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.poglanguage.pogl.pogL.impl.GotoImpl
   * @see org.xtext.poglanguage.pogl.pogL.impl.PogLPackageImpl#getGoto()
   * @generated
   */
  int GOTO = 8;

  /**
   * The feature id for the '<em><b>State name</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GOTO__STATE_NAME = OPERATION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Goto</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GOTO_FEATURE_COUNT = OPERATION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.poglanguage.pogl.pogL.impl.ShowImpl <em>Show</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.poglanguage.pogl.pogL.impl.ShowImpl
   * @see org.xtext.poglanguage.pogl.pogL.impl.PogLPackageImpl#getShow()
   * @generated
   */
  int SHOW = 9;

  /**
   * The feature id for the '<em><b>Text</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SHOW__TEXT = OPERATION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Show</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SHOW_FEATURE_COUNT = OPERATION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.poglanguage.pogl.pogL.impl.OperationsImpl <em>Operations</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.poglanguage.pogl.pogL.impl.OperationsImpl
   * @see org.xtext.poglanguage.pogl.pogL.impl.PogLPackageImpl#getOperations()
   * @generated
   */
  int OPERATIONS = 11;

  /**
   * The feature id for the '<em><b>Operation</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPERATIONS__OPERATION = 0;

  /**
   * The feature id for the '<em><b>Foperations</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPERATIONS__FOPERATIONS = 1;

  /**
   * The number of structural features of the '<em>Operations</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPERATIONS_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.poglanguage.pogl.pogL.impl.FOperationsImpl <em>FOperations</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.poglanguage.pogl.pogL.impl.FOperationsImpl
   * @see org.xtext.poglanguage.pogl.pogL.impl.PogLPackageImpl#getFOperations()
   * @generated
   */
  int FOPERATIONS = 12;

  /**
   * The feature id for the '<em><b>Operations</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FOPERATIONS__OPERATIONS = 0;

  /**
   * The number of structural features of the '<em>FOperations</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FOPERATIONS_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.poglanguage.pogl.pogL.impl.CheckImpl <em>Check</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.poglanguage.pogl.pogL.impl.CheckImpl
   * @see org.xtext.poglanguage.pogl.pogL.impl.PogLPackageImpl#getCheck()
   * @generated
   */
  int CHECK = 13;

  /**
   * The feature id for the '<em><b>Fcheck</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHECK__FCHECK = OPERATION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Check</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHECK_FEATURE_COUNT = OPERATION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.poglanguage.pogl.pogL.impl.FCheckImpl <em>FCheck</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.poglanguage.pogl.pogL.impl.FCheckImpl
   * @see org.xtext.poglanguage.pogl.pogL.impl.PogLPackageImpl#getFCheck()
   * @generated
   */
  int FCHECK = 14;

  /**
   * The feature id for the '<em><b>Item</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FCHECK__ITEM = 0;

  /**
   * The feature id for the '<em><b>FCheck item</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FCHECK__FCHECK_ITEM = 1;

  /**
   * The number of structural features of the '<em>FCheck</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FCHECK_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.poglanguage.pogl.pogL.impl.FCheck_itemImpl <em>FCheck item</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.poglanguage.pogl.pogL.impl.FCheck_itemImpl
   * @see org.xtext.poglanguage.pogl.pogL.impl.PogLPackageImpl#getFCheck_item()
   * @generated
   */
  int FCHECK_ITEM = 15;

  /**
   * The feature id for the '<em><b>Comparison Operator</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FCHECK_ITEM__COMPARISON_OPERATOR = 0;

  /**
   * The feature id for the '<em><b>FComparison Operators</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FCHECK_ITEM__FCOMPARISON_OPERATORS = 1;

  /**
   * The number of structural features of the '<em>FCheck item</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FCHECK_ITEM_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.poglanguage.pogl.pogL.impl.FComparison_OperatorsImpl <em>FComparison Operators</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.poglanguage.pogl.pogL.impl.FComparison_OperatorsImpl
   * @see org.xtext.poglanguage.pogl.pogL.impl.PogLPackageImpl#getFComparison_Operators()
   * @generated
   */
  int FCOMPARISON_OPERATORS = 16;

  /**
   * The number of structural features of the '<em>FComparison Operators</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FCOMPARISON_OPERATORS_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.xtext.poglanguage.pogl.pogL.impl.FINTImpl <em>FINT</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.poglanguage.pogl.pogL.impl.FINTImpl
   * @see org.xtext.poglanguage.pogl.pogL.impl.PogLPackageImpl#getFINT()
   * @generated
   */
  int FINT = 17;

  /**
   * The number of structural features of the '<em>FINT</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FINT_FEATURE_COUNT = FCOMPARISON_OPERATORS_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.xtext.poglanguage.pogl.pogL.impl.FthenImpl <em>Fthen</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.poglanguage.pogl.pogL.impl.FthenImpl
   * @see org.xtext.poglanguage.pogl.pogL.impl.PogLPackageImpl#getFthen()
   * @generated
   */
  int FTHEN = 18;

  /**
   * The feature id for the '<em><b>Operationtrue</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FTHEN__OPERATIONTRUE = FINT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>FThen Operations</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FTHEN__FTHEN_OPERATIONS = FINT_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Fthen</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FTHEN_FEATURE_COUNT = FINT_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.poglanguage.pogl.pogL.impl.FThenOperationsImpl <em>FThen Operations</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.poglanguage.pogl.pogL.impl.FThenOperationsImpl
   * @see org.xtext.poglanguage.pogl.pogL.impl.PogLPackageImpl#getFThenOperations()
   * @generated
   */
  int FTHEN_OPERATIONS = 19;

  /**
   * The feature id for the '<em><b>Operationfalse</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FTHEN_OPERATIONS__OPERATIONFALSE = 0;

  /**
   * The number of structural features of the '<em>FThen Operations</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FTHEN_OPERATIONS_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.poglanguage.pogl.pogL.impl.ActionImpl <em>Action</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.poglanguage.pogl.pogL.impl.ActionImpl
   * @see org.xtext.poglanguage.pogl.pogL.impl.PogLPackageImpl#getAction()
   * @generated
   */
  int ACTION = 20;

  /**
   * The feature id for the '<em><b>State name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTION__STATE_NAME = OPERATION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Description</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTION__DESCRIPTION = OPERATION_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Operations</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTION__OPERATIONS = OPERATION_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Action</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTION_FEATURE_COUNT = OPERATION_FEATURE_COUNT + 3;


  /**
   * Returns the meta object for class '{@link org.xtext.poglanguage.pogl.pogL.Program <em>Program</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Program</em>'.
   * @see org.xtext.poglanguage.pogl.pogL.Program
   * @generated
   */
  EClass getProgram();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.poglanguage.pogl.pogL.Program#getModels <em>Models</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Models</em>'.
   * @see org.xtext.poglanguage.pogl.pogL.Program#getModels()
   * @see #getProgram()
   * @generated
   */
  EReference getProgram_Models();

  /**
   * Returns the meta object for class '{@link org.xtext.poglanguage.pogl.pogL.Model <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Model</em>'.
   * @see org.xtext.poglanguage.pogl.pogL.Model
   * @generated
   */
  EClass getModel();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.poglanguage.pogl.pogL.Model#getModel <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Model</em>'.
   * @see org.xtext.poglanguage.pogl.pogL.Model#getModel()
   * @see #getModel()
   * @generated
   */
  EReference getModel_Model();

  /**
   * Returns the meta object for class '{@link org.xtext.poglanguage.pogl.pogL.State <em>State</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>State</em>'.
   * @see org.xtext.poglanguage.pogl.pogL.State
   * @generated
   */
  EClass getState();

  /**
   * Returns the meta object for class '{@link org.xtext.poglanguage.pogl.pogL.Fstate <em>Fstate</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Fstate</em>'.
   * @see org.xtext.poglanguage.pogl.pogL.Fstate
   * @generated
   */
  EClass getFstate();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.poglanguage.pogl.pogL.Fstate#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.poglanguage.pogl.pogL.Fstate#getName()
   * @see #getFstate()
   * @generated
   */
  EAttribute getFstate_Name();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.poglanguage.pogl.pogL.Fstate#getFstate_name <em>Fstate name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Fstate name</em>'.
   * @see org.xtext.poglanguage.pogl.pogL.Fstate#getFstate_name()
   * @see #getFstate()
   * @generated
   */
  EReference getFstate_Fstate_name();

  /**
   * Returns the meta object for class '{@link org.xtext.poglanguage.pogl.pogL.Fstate_name <em>Fstate name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Fstate name</em>'.
   * @see org.xtext.poglanguage.pogl.pogL.Fstate_name
   * @generated
   */
  EClass getFstate_name();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.poglanguage.pogl.pogL.Fstate_name#getDescription <em>Description</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Description</em>'.
   * @see org.xtext.poglanguage.pogl.pogL.Fstate_name#getDescription()
   * @see #getFstate_name()
   * @generated
   */
  EAttribute getFstate_name_Description();

  /**
   * Returns the meta object for class '{@link org.xtext.poglanguage.pogl.pogL.Item <em>Item</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Item</em>'.
   * @see org.xtext.poglanguage.pogl.pogL.Item
   * @generated
   */
  EClass getItem();

  /**
   * Returns the meta object for class '{@link org.xtext.poglanguage.pogl.pogL.Fitem <em>Fitem</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Fitem</em>'.
   * @see org.xtext.poglanguage.pogl.pogL.Fitem
   * @generated
   */
  EClass getFitem();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.poglanguage.pogl.pogL.Fitem#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.poglanguage.pogl.pogL.Fitem#getName()
   * @see #getFitem()
   * @generated
   */
  EAttribute getFitem_Name();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.poglanguage.pogl.pogL.Fitem#getFitem_name <em>Fitem name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Fitem name</em>'.
   * @see org.xtext.poglanguage.pogl.pogL.Fitem#getFitem_name()
   * @see #getFitem()
   * @generated
   */
  EReference getFitem_Fitem_name();

  /**
   * Returns the meta object for class '{@link org.xtext.poglanguage.pogl.pogL.Fitem_name <em>Fitem name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Fitem name</em>'.
   * @see org.xtext.poglanguage.pogl.pogL.Fitem_name
   * @generated
   */
  EClass getFitem_name();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.poglanguage.pogl.pogL.Fitem_name#getAmount <em>Amount</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Amount</em>'.
   * @see org.xtext.poglanguage.pogl.pogL.Fitem_name#getAmount()
   * @see #getFitem_name()
   * @generated
   */
  EAttribute getFitem_name_Amount();

  /**
   * Returns the meta object for class '{@link org.xtext.poglanguage.pogl.pogL.Goto <em>Goto</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Goto</em>'.
   * @see org.xtext.poglanguage.pogl.pogL.Goto
   * @generated
   */
  EClass getGoto();

  /**
   * Returns the meta object for the reference '{@link org.xtext.poglanguage.pogl.pogL.Goto#getState_name <em>State name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>State name</em>'.
   * @see org.xtext.poglanguage.pogl.pogL.Goto#getState_name()
   * @see #getGoto()
   * @generated
   */
  EReference getGoto_State_name();

  /**
   * Returns the meta object for class '{@link org.xtext.poglanguage.pogl.pogL.Show <em>Show</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Show</em>'.
   * @see org.xtext.poglanguage.pogl.pogL.Show
   * @generated
   */
  EClass getShow();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.poglanguage.pogl.pogL.Show#getText <em>Text</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Text</em>'.
   * @see org.xtext.poglanguage.pogl.pogL.Show#getText()
   * @see #getShow()
   * @generated
   */
  EAttribute getShow_Text();

  /**
   * Returns the meta object for class '{@link org.xtext.poglanguage.pogl.pogL.Operation <em>Operation</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Operation</em>'.
   * @see org.xtext.poglanguage.pogl.pogL.Operation
   * @generated
   */
  EClass getOperation();

  /**
   * Returns the meta object for class '{@link org.xtext.poglanguage.pogl.pogL.Operations <em>Operations</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Operations</em>'.
   * @see org.xtext.poglanguage.pogl.pogL.Operations
   * @generated
   */
  EClass getOperations();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.poglanguage.pogl.pogL.Operations#getOperation <em>Operation</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Operation</em>'.
   * @see org.xtext.poglanguage.pogl.pogL.Operations#getOperation()
   * @see #getOperations()
   * @generated
   */
  EReference getOperations_Operation();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.poglanguage.pogl.pogL.Operations#getFoperations <em>Foperations</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Foperations</em>'.
   * @see org.xtext.poglanguage.pogl.pogL.Operations#getFoperations()
   * @see #getOperations()
   * @generated
   */
  EReference getOperations_Foperations();

  /**
   * Returns the meta object for class '{@link org.xtext.poglanguage.pogl.pogL.FOperations <em>FOperations</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>FOperations</em>'.
   * @see org.xtext.poglanguage.pogl.pogL.FOperations
   * @generated
   */
  EClass getFOperations();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.poglanguage.pogl.pogL.FOperations#getOperations <em>Operations</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Operations</em>'.
   * @see org.xtext.poglanguage.pogl.pogL.FOperations#getOperations()
   * @see #getFOperations()
   * @generated
   */
  EReference getFOperations_Operations();

  /**
   * Returns the meta object for class '{@link org.xtext.poglanguage.pogl.pogL.Check <em>Check</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Check</em>'.
   * @see org.xtext.poglanguage.pogl.pogL.Check
   * @generated
   */
  EClass getCheck();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.poglanguage.pogl.pogL.Check#getFcheck <em>Fcheck</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Fcheck</em>'.
   * @see org.xtext.poglanguage.pogl.pogL.Check#getFcheck()
   * @see #getCheck()
   * @generated
   */
  EReference getCheck_Fcheck();

  /**
   * Returns the meta object for class '{@link org.xtext.poglanguage.pogl.pogL.FCheck <em>FCheck</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>FCheck</em>'.
   * @see org.xtext.poglanguage.pogl.pogL.FCheck
   * @generated
   */
  EClass getFCheck();

  /**
   * Returns the meta object for the reference '{@link org.xtext.poglanguage.pogl.pogL.FCheck#getItem <em>Item</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Item</em>'.
   * @see org.xtext.poglanguage.pogl.pogL.FCheck#getItem()
   * @see #getFCheck()
   * @generated
   */
  EReference getFCheck_Item();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.poglanguage.pogl.pogL.FCheck#getFCheck_item <em>FCheck item</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>FCheck item</em>'.
   * @see org.xtext.poglanguage.pogl.pogL.FCheck#getFCheck_item()
   * @see #getFCheck()
   * @generated
   */
  EReference getFCheck_FCheck_item();

  /**
   * Returns the meta object for class '{@link org.xtext.poglanguage.pogl.pogL.FCheck_item <em>FCheck item</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>FCheck item</em>'.
   * @see org.xtext.poglanguage.pogl.pogL.FCheck_item
   * @generated
   */
  EClass getFCheck_item();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.poglanguage.pogl.pogL.FCheck_item#getComparisonOperator <em>Comparison Operator</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Comparison Operator</em>'.
   * @see org.xtext.poglanguage.pogl.pogL.FCheck_item#getComparisonOperator()
   * @see #getFCheck_item()
   * @generated
   */
  EAttribute getFCheck_item_ComparisonOperator();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.poglanguage.pogl.pogL.FCheck_item#getFComparison_Operators <em>FComparison Operators</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>FComparison Operators</em>'.
   * @see org.xtext.poglanguage.pogl.pogL.FCheck_item#getFComparison_Operators()
   * @see #getFCheck_item()
   * @generated
   */
  EReference getFCheck_item_FComparison_Operators();

  /**
   * Returns the meta object for class '{@link org.xtext.poglanguage.pogl.pogL.FComparison_Operators <em>FComparison Operators</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>FComparison Operators</em>'.
   * @see org.xtext.poglanguage.pogl.pogL.FComparison_Operators
   * @generated
   */
  EClass getFComparison_Operators();

  /**
   * Returns the meta object for class '{@link org.xtext.poglanguage.pogl.pogL.FINT <em>FINT</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>FINT</em>'.
   * @see org.xtext.poglanguage.pogl.pogL.FINT
   * @generated
   */
  EClass getFINT();

  /**
   * Returns the meta object for class '{@link org.xtext.poglanguage.pogl.pogL.Fthen <em>Fthen</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Fthen</em>'.
   * @see org.xtext.poglanguage.pogl.pogL.Fthen
   * @generated
   */
  EClass getFthen();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.poglanguage.pogl.pogL.Fthen#getOperationtrue <em>Operationtrue</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Operationtrue</em>'.
   * @see org.xtext.poglanguage.pogl.pogL.Fthen#getOperationtrue()
   * @see #getFthen()
   * @generated
   */
  EReference getFthen_Operationtrue();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.poglanguage.pogl.pogL.Fthen#getFThenOperations <em>FThen Operations</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>FThen Operations</em>'.
   * @see org.xtext.poglanguage.pogl.pogL.Fthen#getFThenOperations()
   * @see #getFthen()
   * @generated
   */
  EReference getFthen_FThenOperations();

  /**
   * Returns the meta object for class '{@link org.xtext.poglanguage.pogl.pogL.FThenOperations <em>FThen Operations</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>FThen Operations</em>'.
   * @see org.xtext.poglanguage.pogl.pogL.FThenOperations
   * @generated
   */
  EClass getFThenOperations();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.poglanguage.pogl.pogL.FThenOperations#getOperationfalse <em>Operationfalse</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Operationfalse</em>'.
   * @see org.xtext.poglanguage.pogl.pogL.FThenOperations#getOperationfalse()
   * @see #getFThenOperations()
   * @generated
   */
  EReference getFThenOperations_Operationfalse();

  /**
   * Returns the meta object for class '{@link org.xtext.poglanguage.pogl.pogL.Action <em>Action</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Action</em>'.
   * @see org.xtext.poglanguage.pogl.pogL.Action
   * @generated
   */
  EClass getAction();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.poglanguage.pogl.pogL.Action#getState_name <em>State name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>State name</em>'.
   * @see org.xtext.poglanguage.pogl.pogL.Action#getState_name()
   * @see #getAction()
   * @generated
   */
  EAttribute getAction_State_name();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.poglanguage.pogl.pogL.Action#getDescription <em>Description</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Description</em>'.
   * @see org.xtext.poglanguage.pogl.pogL.Action#getDescription()
   * @see #getAction()
   * @generated
   */
  EAttribute getAction_Description();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.poglanguage.pogl.pogL.Action#getOperations <em>Operations</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Operations</em>'.
   * @see org.xtext.poglanguage.pogl.pogL.Action#getOperations()
   * @see #getAction()
   * @generated
   */
  EReference getAction_Operations();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  PogLFactory getPogLFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.poglanguage.pogl.pogL.impl.ProgramImpl <em>Program</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.poglanguage.pogl.pogL.impl.ProgramImpl
     * @see org.xtext.poglanguage.pogl.pogL.impl.PogLPackageImpl#getProgram()
     * @generated
     */
    EClass PROGRAM = eINSTANCE.getProgram();

    /**
     * The meta object literal for the '<em><b>Models</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PROGRAM__MODELS = eINSTANCE.getProgram_Models();

    /**
     * The meta object literal for the '{@link org.xtext.poglanguage.pogl.pogL.impl.ModelImpl <em>Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.poglanguage.pogl.pogL.impl.ModelImpl
     * @see org.xtext.poglanguage.pogl.pogL.impl.PogLPackageImpl#getModel()
     * @generated
     */
    EClass MODEL = eINSTANCE.getModel();

    /**
     * The meta object literal for the '<em><b>Model</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__MODEL = eINSTANCE.getModel_Model();

    /**
     * The meta object literal for the '{@link org.xtext.poglanguage.pogl.pogL.impl.StateImpl <em>State</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.poglanguage.pogl.pogL.impl.StateImpl
     * @see org.xtext.poglanguage.pogl.pogL.impl.PogLPackageImpl#getState()
     * @generated
     */
    EClass STATE = eINSTANCE.getState();

    /**
     * The meta object literal for the '{@link org.xtext.poglanguage.pogl.pogL.impl.FstateImpl <em>Fstate</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.poglanguage.pogl.pogL.impl.FstateImpl
     * @see org.xtext.poglanguage.pogl.pogL.impl.PogLPackageImpl#getFstate()
     * @generated
     */
    EClass FSTATE = eINSTANCE.getFstate();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FSTATE__NAME = eINSTANCE.getFstate_Name();

    /**
     * The meta object literal for the '<em><b>Fstate name</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FSTATE__FSTATE_NAME = eINSTANCE.getFstate_Fstate_name();

    /**
     * The meta object literal for the '{@link org.xtext.poglanguage.pogl.pogL.impl.Fstate_nameImpl <em>Fstate name</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.poglanguage.pogl.pogL.impl.Fstate_nameImpl
     * @see org.xtext.poglanguage.pogl.pogL.impl.PogLPackageImpl#getFstate_name()
     * @generated
     */
    EClass FSTATE_NAME = eINSTANCE.getFstate_name();

    /**
     * The meta object literal for the '<em><b>Description</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FSTATE_NAME__DESCRIPTION = eINSTANCE.getFstate_name_Description();

    /**
     * The meta object literal for the '{@link org.xtext.poglanguage.pogl.pogL.impl.ItemImpl <em>Item</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.poglanguage.pogl.pogL.impl.ItemImpl
     * @see org.xtext.poglanguage.pogl.pogL.impl.PogLPackageImpl#getItem()
     * @generated
     */
    EClass ITEM = eINSTANCE.getItem();

    /**
     * The meta object literal for the '{@link org.xtext.poglanguage.pogl.pogL.impl.FitemImpl <em>Fitem</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.poglanguage.pogl.pogL.impl.FitemImpl
     * @see org.xtext.poglanguage.pogl.pogL.impl.PogLPackageImpl#getFitem()
     * @generated
     */
    EClass FITEM = eINSTANCE.getFitem();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FITEM__NAME = eINSTANCE.getFitem_Name();

    /**
     * The meta object literal for the '<em><b>Fitem name</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FITEM__FITEM_NAME = eINSTANCE.getFitem_Fitem_name();

    /**
     * The meta object literal for the '{@link org.xtext.poglanguage.pogl.pogL.impl.Fitem_nameImpl <em>Fitem name</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.poglanguage.pogl.pogL.impl.Fitem_nameImpl
     * @see org.xtext.poglanguage.pogl.pogL.impl.PogLPackageImpl#getFitem_name()
     * @generated
     */
    EClass FITEM_NAME = eINSTANCE.getFitem_name();

    /**
     * The meta object literal for the '<em><b>Amount</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FITEM_NAME__AMOUNT = eINSTANCE.getFitem_name_Amount();

    /**
     * The meta object literal for the '{@link org.xtext.poglanguage.pogl.pogL.impl.GotoImpl <em>Goto</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.poglanguage.pogl.pogL.impl.GotoImpl
     * @see org.xtext.poglanguage.pogl.pogL.impl.PogLPackageImpl#getGoto()
     * @generated
     */
    EClass GOTO = eINSTANCE.getGoto();

    /**
     * The meta object literal for the '<em><b>State name</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference GOTO__STATE_NAME = eINSTANCE.getGoto_State_name();

    /**
     * The meta object literal for the '{@link org.xtext.poglanguage.pogl.pogL.impl.ShowImpl <em>Show</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.poglanguage.pogl.pogL.impl.ShowImpl
     * @see org.xtext.poglanguage.pogl.pogL.impl.PogLPackageImpl#getShow()
     * @generated
     */
    EClass SHOW = eINSTANCE.getShow();

    /**
     * The meta object literal for the '<em><b>Text</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SHOW__TEXT = eINSTANCE.getShow_Text();

    /**
     * The meta object literal for the '{@link org.xtext.poglanguage.pogl.pogL.impl.OperationImpl <em>Operation</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.poglanguage.pogl.pogL.impl.OperationImpl
     * @see org.xtext.poglanguage.pogl.pogL.impl.PogLPackageImpl#getOperation()
     * @generated
     */
    EClass OPERATION = eINSTANCE.getOperation();

    /**
     * The meta object literal for the '{@link org.xtext.poglanguage.pogl.pogL.impl.OperationsImpl <em>Operations</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.poglanguage.pogl.pogL.impl.OperationsImpl
     * @see org.xtext.poglanguage.pogl.pogL.impl.PogLPackageImpl#getOperations()
     * @generated
     */
    EClass OPERATIONS = eINSTANCE.getOperations();

    /**
     * The meta object literal for the '<em><b>Operation</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference OPERATIONS__OPERATION = eINSTANCE.getOperations_Operation();

    /**
     * The meta object literal for the '<em><b>Foperations</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference OPERATIONS__FOPERATIONS = eINSTANCE.getOperations_Foperations();

    /**
     * The meta object literal for the '{@link org.xtext.poglanguage.pogl.pogL.impl.FOperationsImpl <em>FOperations</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.poglanguage.pogl.pogL.impl.FOperationsImpl
     * @see org.xtext.poglanguage.pogl.pogL.impl.PogLPackageImpl#getFOperations()
     * @generated
     */
    EClass FOPERATIONS = eINSTANCE.getFOperations();

    /**
     * The meta object literal for the '<em><b>Operations</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FOPERATIONS__OPERATIONS = eINSTANCE.getFOperations_Operations();

    /**
     * The meta object literal for the '{@link org.xtext.poglanguage.pogl.pogL.impl.CheckImpl <em>Check</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.poglanguage.pogl.pogL.impl.CheckImpl
     * @see org.xtext.poglanguage.pogl.pogL.impl.PogLPackageImpl#getCheck()
     * @generated
     */
    EClass CHECK = eINSTANCE.getCheck();

    /**
     * The meta object literal for the '<em><b>Fcheck</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CHECK__FCHECK = eINSTANCE.getCheck_Fcheck();

    /**
     * The meta object literal for the '{@link org.xtext.poglanguage.pogl.pogL.impl.FCheckImpl <em>FCheck</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.poglanguage.pogl.pogL.impl.FCheckImpl
     * @see org.xtext.poglanguage.pogl.pogL.impl.PogLPackageImpl#getFCheck()
     * @generated
     */
    EClass FCHECK = eINSTANCE.getFCheck();

    /**
     * The meta object literal for the '<em><b>Item</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FCHECK__ITEM = eINSTANCE.getFCheck_Item();

    /**
     * The meta object literal for the '<em><b>FCheck item</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FCHECK__FCHECK_ITEM = eINSTANCE.getFCheck_FCheck_item();

    /**
     * The meta object literal for the '{@link org.xtext.poglanguage.pogl.pogL.impl.FCheck_itemImpl <em>FCheck item</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.poglanguage.pogl.pogL.impl.FCheck_itemImpl
     * @see org.xtext.poglanguage.pogl.pogL.impl.PogLPackageImpl#getFCheck_item()
     * @generated
     */
    EClass FCHECK_ITEM = eINSTANCE.getFCheck_item();

    /**
     * The meta object literal for the '<em><b>Comparison Operator</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FCHECK_ITEM__COMPARISON_OPERATOR = eINSTANCE.getFCheck_item_ComparisonOperator();

    /**
     * The meta object literal for the '<em><b>FComparison Operators</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FCHECK_ITEM__FCOMPARISON_OPERATORS = eINSTANCE.getFCheck_item_FComparison_Operators();

    /**
     * The meta object literal for the '{@link org.xtext.poglanguage.pogl.pogL.impl.FComparison_OperatorsImpl <em>FComparison Operators</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.poglanguage.pogl.pogL.impl.FComparison_OperatorsImpl
     * @see org.xtext.poglanguage.pogl.pogL.impl.PogLPackageImpl#getFComparison_Operators()
     * @generated
     */
    EClass FCOMPARISON_OPERATORS = eINSTANCE.getFComparison_Operators();

    /**
     * The meta object literal for the '{@link org.xtext.poglanguage.pogl.pogL.impl.FINTImpl <em>FINT</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.poglanguage.pogl.pogL.impl.FINTImpl
     * @see org.xtext.poglanguage.pogl.pogL.impl.PogLPackageImpl#getFINT()
     * @generated
     */
    EClass FINT = eINSTANCE.getFINT();

    /**
     * The meta object literal for the '{@link org.xtext.poglanguage.pogl.pogL.impl.FthenImpl <em>Fthen</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.poglanguage.pogl.pogL.impl.FthenImpl
     * @see org.xtext.poglanguage.pogl.pogL.impl.PogLPackageImpl#getFthen()
     * @generated
     */
    EClass FTHEN = eINSTANCE.getFthen();

    /**
     * The meta object literal for the '<em><b>Operationtrue</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FTHEN__OPERATIONTRUE = eINSTANCE.getFthen_Operationtrue();

    /**
     * The meta object literal for the '<em><b>FThen Operations</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FTHEN__FTHEN_OPERATIONS = eINSTANCE.getFthen_FThenOperations();

    /**
     * The meta object literal for the '{@link org.xtext.poglanguage.pogl.pogL.impl.FThenOperationsImpl <em>FThen Operations</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.poglanguage.pogl.pogL.impl.FThenOperationsImpl
     * @see org.xtext.poglanguage.pogl.pogL.impl.PogLPackageImpl#getFThenOperations()
     * @generated
     */
    EClass FTHEN_OPERATIONS = eINSTANCE.getFThenOperations();

    /**
     * The meta object literal for the '<em><b>Operationfalse</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FTHEN_OPERATIONS__OPERATIONFALSE = eINSTANCE.getFThenOperations_Operationfalse();

    /**
     * The meta object literal for the '{@link org.xtext.poglanguage.pogl.pogL.impl.ActionImpl <em>Action</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.poglanguage.pogl.pogL.impl.ActionImpl
     * @see org.xtext.poglanguage.pogl.pogL.impl.PogLPackageImpl#getAction()
     * @generated
     */
    EClass ACTION = eINSTANCE.getAction();

    /**
     * The meta object literal for the '<em><b>State name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ACTION__STATE_NAME = eINSTANCE.getAction_State_name();

    /**
     * The meta object literal for the '<em><b>Description</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ACTION__DESCRIPTION = eINSTANCE.getAction_Description();

    /**
     * The meta object literal for the '<em><b>Operations</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ACTION__OPERATIONS = eINSTANCE.getAction_Operations();

  }

} //PogLPackage
