/**
 * generated by Xtext 2.30.0
 */
package org.xtext.poglanguage.pogl.pogL;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>State</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.poglanguage.pogl.pogL.PogLPackage#getState()
 * @model
 * @generated
 */
public interface State extends Operation
{
} // State
