/*
 * generated by Xtext 2.30.0
 */
package org.xtext.poglanguage.pogl.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractPogLValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(org.xtext.poglanguage.pogl.pogL.PogLPackage.eINSTANCE);
		return result;
	}
}
