/*
 * generated by Xtext 2.30.0
 */
package org.xtext.poglanguage.pogl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class PogLUiModule extends AbstractPogLUiModule {

	public PogLUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
