/*
 * generated by Xtext 2.29.0
 */
package org.dungeonsanddomains.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class POGLUiModule extends AbstractPOGLUiModule {

	public POGLUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
