/*
 * generated by Xtext 2.30.0
 */
package org.xtext.poglanguage.pogl;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class PogLRuntimeModule extends AbstractPogLRuntimeModule {
}
