/* This file was generated by SableCC (http://www.sablecc.org/). */

package exercise40_fischer.node;

import exercise40_fischer.analysis.*;

@SuppressWarnings("nls")
public final class AOneStmt extends PStmt
{
    private TIf _if_;
    private TE _e_;
    private TThen _then_;
    private PStmt _fst_;
    private TElse _else_;
    private PStmt _snd_;

    public AOneStmt()
    {
        // Constructor
    }

    public AOneStmt(
        @SuppressWarnings("hiding") TIf _if_,
        @SuppressWarnings("hiding") TE _e_,
        @SuppressWarnings("hiding") TThen _then_,
        @SuppressWarnings("hiding") PStmt _fst_,
        @SuppressWarnings("hiding") TElse _else_,
        @SuppressWarnings("hiding") PStmt _snd_)
    {
        // Constructor
        setIf(_if_);

        setE(_e_);

        setThen(_then_);

        setFst(_fst_);

        setElse(_else_);

        setSnd(_snd_);

    }

    @Override
    public Object clone()
    {
        return new AOneStmt(
            cloneNode(this._if_),
            cloneNode(this._e_),
            cloneNode(this._then_),
            cloneNode(this._fst_),
            cloneNode(this._else_),
            cloneNode(this._snd_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAOneStmt(this);
    }

    public TIf getIf()
    {
        return this._if_;
    }

    public void setIf(TIf node)
    {
        if(this._if_ != null)
        {
            this._if_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._if_ = node;
    }

    public TE getE()
    {
        return this._e_;
    }

    public void setE(TE node)
    {
        if(this._e_ != null)
        {
            this._e_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._e_ = node;
    }

    public TThen getThen()
    {
        return this._then_;
    }

    public void setThen(TThen node)
    {
        if(this._then_ != null)
        {
            this._then_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._then_ = node;
    }

    public PStmt getFst()
    {
        return this._fst_;
    }

    public void setFst(PStmt node)
    {
        if(this._fst_ != null)
        {
            this._fst_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._fst_ = node;
    }

    public TElse getElse()
    {
        return this._else_;
    }

    public void setElse(TElse node)
    {
        if(this._else_ != null)
        {
            this._else_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._else_ = node;
    }

    public PStmt getSnd()
    {
        return this._snd_;
    }

    public void setSnd(PStmt node)
    {
        if(this._snd_ != null)
        {
            this._snd_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._snd_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._if_)
            + toString(this._e_)
            + toString(this._then_)
            + toString(this._fst_)
            + toString(this._else_)
            + toString(this._snd_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._if_ == child)
        {
            this._if_ = null;
            return;
        }

        if(this._e_ == child)
        {
            this._e_ = null;
            return;
        }

        if(this._then_ == child)
        {
            this._then_ = null;
            return;
        }

        if(this._fst_ == child)
        {
            this._fst_ = null;
            return;
        }

        if(this._else_ == child)
        {
            this._else_ = null;
            return;
        }

        if(this._snd_ == child)
        {
            this._snd_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._if_ == oldChild)
        {
            setIf((TIf) newChild);
            return;
        }

        if(this._e_ == oldChild)
        {
            setE((TE) newChild);
            return;
        }

        if(this._then_ == oldChild)
        {
            setThen((TThen) newChild);
            return;
        }

        if(this._fst_ == oldChild)
        {
            setFst((PStmt) newChild);
            return;
        }

        if(this._else_ == oldChild)
        {
            setElse((TElse) newChild);
            return;
        }

        if(this._snd_ == oldChild)
        {
            setSnd((PStmt) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
