/* This file was generated by SableCC (http://www.sablecc.org/). */

package exercise40_fischer.node;

import exercise40_fischer.analysis.*;

@SuppressWarnings("nls")
public final class AThreeStmt extends PStmt
{
    private TOther _other_;

    public AThreeStmt()
    {
        // Constructor
    }

    public AThreeStmt(
        @SuppressWarnings("hiding") TOther _other_)
    {
        // Constructor
        setOther(_other_);

    }

    @Override
    public Object clone()
    {
        return new AThreeStmt(
            cloneNode(this._other_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAThreeStmt(this);
    }

    public TOther getOther()
    {
        return this._other_;
    }

    public void setOther(TOther node)
    {
        if(this._other_ != null)
        {
            this._other_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._other_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._other_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._other_ == child)
        {
            this._other_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._other_ == oldChild)
        {
            setOther((TOther) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
