/*
 * generated by Xtext 2.30.0
 */
package org.xtext.poglanguage.pogl.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.poglanguage.pogl.PogLRuntimeModule;
import org.xtext.poglanguage.pogl.PogLStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class PogLIdeSetup extends PogLStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new PogLRuntimeModule(), new PogLIdeModule()));
	}
	
}
