/*
 * generated by Xtext 2.30.0
 */
package org.xtext.poglanguage.pogl.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;
import org.xtext.poglanguage.pogl.ui.internal.PoglActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class PogLExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(PoglActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		PoglActivator activator = PoglActivator.getInstance();
		return activator != null ? activator.getInjector(PoglActivator.ORG_XTEXT_POGLANGUAGE_POGL_POGL) : null;
	}

}
