/*
 * generated by Xtext 2.29.0
 */
package org.dungeonsanddomains;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class POGLStandaloneSetup extends POGLStandaloneSetupGenerated {

	public static void doSetup() {
		new POGLStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
