/*
 * generated by Xtext 2.29.0
 */
package org.dungeonsanddomains;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class POGLRuntimeModule extends AbstractPOGLRuntimeModule {
}
