/* This file was generated by SableCC (http://www.sablecc.org/). */

package exercise40_fischer.analysis;

import exercise40_fischer.node.*;

public interface Analysis extends Switch
{
    Object getIn(Node node);
    void setIn(Node node, Object o);
    Object getOut(Node node);
    void setOut(Node node, Object o);

    void caseStart(Start node);
    void caseAStart(AStart node);
    void caseAOneStmt(AOneStmt node);
    void caseATwoStmt(ATwoStmt node);
    void caseAThreeStmt(AThreeStmt node);

    void caseTE(TE node);
    void caseTOther(TOther node);
    void caseTIf(TIf node);
    void caseTThen(TThen node);
    void caseTElse(TElse node);
    void caseTBlank(TBlank node);
    void caseEOF(EOF node);
    void caseInvalidToken(InvalidToken node);
}
