/*
 * generated by Xtext 2.30.0
 */
package org.xtext.poglanguage.pogl.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.poglanguage.pogl.parser.antlr.internal.InternalPogLParser;
import org.xtext.poglanguage.pogl.services.PogLGrammarAccess;

public class PogLParser extends AbstractAntlrParser {

	@Inject
	private PogLGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalPogLParser createParser(XtextTokenStream stream) {
		return new InternalPogLParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Program";
	}

	public PogLGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(PogLGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
