/*
 * generated by Xtext 2.30.0
 */
package org.xtext.poglanguage.pogl.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;
import org.xtext.poglanguage.pogl.ide.contentassist.antlr.internal.InternalPogLParser;
import org.xtext.poglanguage.pogl.services.PogLGrammarAccess;

public class PogLParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(PogLGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, PogLGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getModelAccess().getModelAlternatives_0(), "rule__Model__ModelAlternatives_0");
			builder.put(grammarAccess.getFstate_nameAccess().getAlternatives(), "rule__Fstate_name__Alternatives");
			builder.put(grammarAccess.getFitem_nameAccess().getAlternatives(), "rule__Fitem_name__Alternatives");
			builder.put(grammarAccess.getOperationAccess().getAlternatives(), "rule__Operation__Alternatives");
			builder.put(grammarAccess.getComparisonOperatorsAccess().getAlternatives(), "rule__ComparisonOperators__Alternatives");
			builder.put(grammarAccess.getFThenOperationsAccess().getAlternatives(), "rule__FThenOperations__Alternatives");
			builder.put(grammarAccess.getStateAccess().getGroup(), "rule__State__Group__0");
			builder.put(grammarAccess.getFstateAccess().getGroup(), "rule__Fstate__Group__0");
			builder.put(grammarAccess.getFstate_nameAccess().getGroup_0(), "rule__Fstate_name__Group_0__0");
			builder.put(grammarAccess.getFstate_nameAccess().getGroup_1(), "rule__Fstate_name__Group_1__0");
			builder.put(grammarAccess.getItemAccess().getGroup(), "rule__Item__Group__0");
			builder.put(grammarAccess.getFitemAccess().getGroup(), "rule__Fitem__Group__0");
			builder.put(grammarAccess.getFitem_nameAccess().getGroup_0(), "rule__Fitem_name__Group_0__0");
			builder.put(grammarAccess.getFitem_nameAccess().getGroup_1(), "rule__Fitem_name__Group_1__0");
			builder.put(grammarAccess.getFitem_nameAccess().getGroup_2(), "rule__Fitem_name__Group_2__0");
			builder.put(grammarAccess.getGotoAccess().getGroup(), "rule__Goto__Group__0");
			builder.put(grammarAccess.getShowAccess().getGroup(), "rule__Show__Group__0");
			builder.put(grammarAccess.getOperationsAccess().getGroup(), "rule__Operations__Group__0");
			builder.put(grammarAccess.getCheckAccess().getGroup(), "rule__Check__Group__0");
			builder.put(grammarAccess.getFCheckAccess().getGroup(), "rule__FCheck__Group__0");
			builder.put(grammarAccess.getFCheck_itemAccess().getGroup(), "rule__FCheck_item__Group__0");
			builder.put(grammarAccess.getFComparison_OperatorsAccess().getGroup(), "rule__FComparison_Operators__Group__0");
			builder.put(grammarAccess.getFINTAccess().getGroup(), "rule__FINT__Group__0");
			builder.put(grammarAccess.getFthenAccess().getGroup(), "rule__Fthen__Group__0");
			builder.put(grammarAccess.getFThenOperationsAccess().getGroup_0(), "rule__FThenOperations__Group_0__0");
			builder.put(grammarAccess.getFThenOperationsAccess().getGroup_1(), "rule__FThenOperations__Group_1__0");
			builder.put(grammarAccess.getActionAccess().getGroup(), "rule__Action__Group__0");
			builder.put(grammarAccess.getProgramAccess().getModelsAssignment(), "rule__Program__ModelsAssignment");
			builder.put(grammarAccess.getModelAccess().getModelAssignment(), "rule__Model__ModelAssignment");
			builder.put(grammarAccess.getFstateAccess().getNameAssignment_0(), "rule__Fstate__NameAssignment_0");
			builder.put(grammarAccess.getFstateAccess().getFstate_nameAssignment_1(), "rule__Fstate__Fstate_nameAssignment_1");
			builder.put(grammarAccess.getFstate_nameAccess().getDescriptionAssignment_0_1(), "rule__Fstate_name__DescriptionAssignment_0_1");
			builder.put(grammarAccess.getFstate_nameAccess().getDescriptionAssignment_1_1(), "rule__Fstate_name__DescriptionAssignment_1_1");
			builder.put(grammarAccess.getFstate_nameAccess().getDescriptionAssignment_2(), "rule__Fstate_name__DescriptionAssignment_2");
			builder.put(grammarAccess.getFitemAccess().getNameAssignment_0(), "rule__Fitem__NameAssignment_0");
			builder.put(grammarAccess.getFitemAccess().getFitem_nameAssignment_1(), "rule__Fitem__Fitem_nameAssignment_1");
			builder.put(grammarAccess.getFitem_nameAccess().getAmountAssignment_0_1(), "rule__Fitem_name__AmountAssignment_0_1");
			builder.put(grammarAccess.getFitem_nameAccess().getAmountAssignment_1_1(), "rule__Fitem_name__AmountAssignment_1_1");
			builder.put(grammarAccess.getFitem_nameAccess().getAmountAssignment_2_1(), "rule__Fitem_name__AmountAssignment_2_1");
			builder.put(grammarAccess.getGotoAccess().getState_nameAssignment_1(), "rule__Goto__State_nameAssignment_1");
			builder.put(grammarAccess.getShowAccess().getTextAssignment_1(), "rule__Show__TextAssignment_1");
			builder.put(grammarAccess.getOperationsAccess().getOperationAssignment_0(), "rule__Operations__OperationAssignment_0");
			builder.put(grammarAccess.getOperationsAccess().getFoperationsAssignment_1(), "rule__Operations__FoperationsAssignment_1");
			builder.put(grammarAccess.getFOperationsAccess().getOperationsAssignment(), "rule__FOperations__OperationsAssignment");
			builder.put(grammarAccess.getCheckAccess().getFcheckAssignment_1(), "rule__Check__FcheckAssignment_1");
			builder.put(grammarAccess.getFCheckAccess().getItemAssignment_0(), "rule__FCheck__ItemAssignment_0");
			builder.put(grammarAccess.getFCheckAccess().getFCheck_itemAssignment_1(), "rule__FCheck__FCheck_itemAssignment_1");
			builder.put(grammarAccess.getFCheck_itemAccess().getComparisonOperatorAssignment_0(), "rule__FCheck_item__ComparisonOperatorAssignment_0");
			builder.put(grammarAccess.getFCheck_itemAccess().getFComparison_OperatorsAssignment_1(), "rule__FCheck_item__FComparison_OperatorsAssignment_1");
			builder.put(grammarAccess.getFthenAccess().getOperationtrueAssignment_0(), "rule__Fthen__OperationtrueAssignment_0");
			builder.put(grammarAccess.getFthenAccess().getFThenOperationsAssignment_1(), "rule__Fthen__FThenOperationsAssignment_1");
			builder.put(grammarAccess.getFThenOperationsAccess().getOperationfalseAssignment_0_1(), "rule__FThenOperations__OperationfalseAssignment_0_1");
			builder.put(grammarAccess.getActionAccess().getState_nameAssignment_2(), "rule__Action__State_nameAssignment_2");
			builder.put(grammarAccess.getActionAccess().getDescriptionAssignment_3(), "rule__Action__DescriptionAssignment_3");
			builder.put(grammarAccess.getActionAccess().getOperationsAssignment_5(), "rule__Action__OperationsAssignment_5");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private PogLGrammarAccess grammarAccess;

	@Override
	protected InternalPogLParser createParser() {
		InternalPogLParser result = new InternalPogLParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public PogLGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(PogLGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
