/**
 * generated by Xtext 2.30.0
 */
package org.xtext.poglanguage.pogl.pogL.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.poglanguage.pogl.pogL.FCheck;
import org.xtext.poglanguage.pogl.pogL.FCheck_item;
import org.xtext.poglanguage.pogl.pogL.Fitem;
import org.xtext.poglanguage.pogl.pogL.PogLPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>FCheck</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.poglanguage.pogl.pogL.impl.FCheckImpl#getItem <em>Item</em>}</li>
 *   <li>{@link org.xtext.poglanguage.pogl.pogL.impl.FCheckImpl#getFCheck_item <em>FCheck item</em>}</li>
 * </ul>
 *
 * @generated
 */
public class FCheckImpl extends MinimalEObjectImpl.Container implements FCheck
{
  /**
   * The cached value of the '{@link #getItem() <em>Item</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getItem()
   * @generated
   * @ordered
   */
  protected Fitem item;

  /**
   * The cached value of the '{@link #getFCheck_item() <em>FCheck item</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getFCheck_item()
   * @generated
   * @ordered
   */
  protected FCheck_item fCheck_item;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected FCheckImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return PogLPackage.Literals.FCHECK;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Fitem getItem()
  {
    if (item != null && item.eIsProxy())
    {
      InternalEObject oldItem = (InternalEObject)item;
      item = (Fitem)eResolveProxy(oldItem);
      if (item != oldItem)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, PogLPackage.FCHECK__ITEM, oldItem, item));
      }
    }
    return item;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Fitem basicGetItem()
  {
    return item;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setItem(Fitem newItem)
  {
    Fitem oldItem = item;
    item = newItem;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, PogLPackage.FCHECK__ITEM, oldItem, item));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public FCheck_item getFCheck_item()
  {
    return fCheck_item;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetFCheck_item(FCheck_item newFCheck_item, NotificationChain msgs)
  {
    FCheck_item oldFCheck_item = fCheck_item;
    fCheck_item = newFCheck_item;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, PogLPackage.FCHECK__FCHECK_ITEM, oldFCheck_item, newFCheck_item);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setFCheck_item(FCheck_item newFCheck_item)
  {
    if (newFCheck_item != fCheck_item)
    {
      NotificationChain msgs = null;
      if (fCheck_item != null)
        msgs = ((InternalEObject)fCheck_item).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - PogLPackage.FCHECK__FCHECK_ITEM, null, msgs);
      if (newFCheck_item != null)
        msgs = ((InternalEObject)newFCheck_item).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - PogLPackage.FCHECK__FCHECK_ITEM, null, msgs);
      msgs = basicSetFCheck_item(newFCheck_item, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, PogLPackage.FCHECK__FCHECK_ITEM, newFCheck_item, newFCheck_item));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case PogLPackage.FCHECK__FCHECK_ITEM:
        return basicSetFCheck_item(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case PogLPackage.FCHECK__ITEM:
        if (resolve) return getItem();
        return basicGetItem();
      case PogLPackage.FCHECK__FCHECK_ITEM:
        return getFCheck_item();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case PogLPackage.FCHECK__ITEM:
        setItem((Fitem)newValue);
        return;
      case PogLPackage.FCHECK__FCHECK_ITEM:
        setFCheck_item((FCheck_item)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case PogLPackage.FCHECK__ITEM:
        setItem((Fitem)null);
        return;
      case PogLPackage.FCHECK__FCHECK_ITEM:
        setFCheck_item((FCheck_item)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case PogLPackage.FCHECK__ITEM:
        return item != null;
      case PogLPackage.FCHECK__FCHECK_ITEM:
        return fCheck_item != null;
    }
    return super.eIsSet(featureID);
  }

} //FCheckImpl
