/**
 * generated by Xtext 2.30.0
 */
package org.xtext.poglanguage.pogl.pogL.impl;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.poglanguage.pogl.pogL.FComparison_Operators;
import org.xtext.poglanguage.pogl.pogL.PogLPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>FComparison Operators</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class FComparison_OperatorsImpl extends MinimalEObjectImpl.Container implements FComparison_Operators
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected FComparison_OperatorsImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return PogLPackage.Literals.FCOMPARISON_OPERATORS;
  }

} //FComparison_OperatorsImpl
