/**
 * generated by Xtext 2.30.0
 */
package org.xtext.poglanguage.pogl.pogL.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.xtext.poglanguage.pogl.pogL.Fitem;
import org.xtext.poglanguage.pogl.pogL.Fitem_name;
import org.xtext.poglanguage.pogl.pogL.PogLPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Fitem</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.poglanguage.pogl.pogL.impl.FitemImpl#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.poglanguage.pogl.pogL.impl.FitemImpl#getFitem_name <em>Fitem name</em>}</li>
 * </ul>
 *
 * @generated
 */
public class FitemImpl extends ItemImpl implements Fitem
{
  /**
   * The default value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected static final String NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected String name = NAME_EDEFAULT;

  /**
   * The cached value of the '{@link #getFitem_name() <em>Fitem name</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getFitem_name()
   * @generated
   * @ordered
   */
  protected Fitem_name fitem_name;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected FitemImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return PogLPackage.Literals.FITEM;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setName(String newName)
  {
    String oldName = name;
    name = newName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, PogLPackage.FITEM__NAME, oldName, name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Fitem_name getFitem_name()
  {
    return fitem_name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetFitem_name(Fitem_name newFitem_name, NotificationChain msgs)
  {
    Fitem_name oldFitem_name = fitem_name;
    fitem_name = newFitem_name;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, PogLPackage.FITEM__FITEM_NAME, oldFitem_name, newFitem_name);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setFitem_name(Fitem_name newFitem_name)
  {
    if (newFitem_name != fitem_name)
    {
      NotificationChain msgs = null;
      if (fitem_name != null)
        msgs = ((InternalEObject)fitem_name).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - PogLPackage.FITEM__FITEM_NAME, null, msgs);
      if (newFitem_name != null)
        msgs = ((InternalEObject)newFitem_name).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - PogLPackage.FITEM__FITEM_NAME, null, msgs);
      msgs = basicSetFitem_name(newFitem_name, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, PogLPackage.FITEM__FITEM_NAME, newFitem_name, newFitem_name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case PogLPackage.FITEM__FITEM_NAME:
        return basicSetFitem_name(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case PogLPackage.FITEM__NAME:
        return getName();
      case PogLPackage.FITEM__FITEM_NAME:
        return getFitem_name();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case PogLPackage.FITEM__NAME:
        setName((String)newValue);
        return;
      case PogLPackage.FITEM__FITEM_NAME:
        setFitem_name((Fitem_name)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case PogLPackage.FITEM__NAME:
        setName(NAME_EDEFAULT);
        return;
      case PogLPackage.FITEM__FITEM_NAME:
        setFitem_name((Fitem_name)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case PogLPackage.FITEM__NAME:
        return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
      case PogLPackage.FITEM__FITEM_NAME:
        return fitem_name != null;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (name: ");
    result.append(name);
    result.append(')');
    return result.toString();
  }

} //FitemImpl
