/**
 * generated by Xtext 2.30.0
 */
package org.xtext.poglanguage.pogl.pogL.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.xtext.poglanguage.pogl.pogL.FThenOperations;
import org.xtext.poglanguage.pogl.pogL.Fthen;
import org.xtext.poglanguage.pogl.pogL.Operations;
import org.xtext.poglanguage.pogl.pogL.PogLPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Fthen</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.poglanguage.pogl.pogL.impl.FthenImpl#getOperationtrue <em>Operationtrue</em>}</li>
 *   <li>{@link org.xtext.poglanguage.pogl.pogL.impl.FthenImpl#getFThenOperations <em>FThen Operations</em>}</li>
 * </ul>
 *
 * @generated
 */
public class FthenImpl extends FINTImpl implements Fthen
{
  /**
   * The cached value of the '{@link #getOperationtrue() <em>Operationtrue</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getOperationtrue()
   * @generated
   * @ordered
   */
  protected Operations operationtrue;

  /**
   * The cached value of the '{@link #getFThenOperations() <em>FThen Operations</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getFThenOperations()
   * @generated
   * @ordered
   */
  protected FThenOperations fThenOperations;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected FthenImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return PogLPackage.Literals.FTHEN;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Operations getOperationtrue()
  {
    return operationtrue;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetOperationtrue(Operations newOperationtrue, NotificationChain msgs)
  {
    Operations oldOperationtrue = operationtrue;
    operationtrue = newOperationtrue;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, PogLPackage.FTHEN__OPERATIONTRUE, oldOperationtrue, newOperationtrue);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setOperationtrue(Operations newOperationtrue)
  {
    if (newOperationtrue != operationtrue)
    {
      NotificationChain msgs = null;
      if (operationtrue != null)
        msgs = ((InternalEObject)operationtrue).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - PogLPackage.FTHEN__OPERATIONTRUE, null, msgs);
      if (newOperationtrue != null)
        msgs = ((InternalEObject)newOperationtrue).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - PogLPackage.FTHEN__OPERATIONTRUE, null, msgs);
      msgs = basicSetOperationtrue(newOperationtrue, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, PogLPackage.FTHEN__OPERATIONTRUE, newOperationtrue, newOperationtrue));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public FThenOperations getFThenOperations()
  {
    return fThenOperations;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetFThenOperations(FThenOperations newFThenOperations, NotificationChain msgs)
  {
    FThenOperations oldFThenOperations = fThenOperations;
    fThenOperations = newFThenOperations;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, PogLPackage.FTHEN__FTHEN_OPERATIONS, oldFThenOperations, newFThenOperations);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setFThenOperations(FThenOperations newFThenOperations)
  {
    if (newFThenOperations != fThenOperations)
    {
      NotificationChain msgs = null;
      if (fThenOperations != null)
        msgs = ((InternalEObject)fThenOperations).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - PogLPackage.FTHEN__FTHEN_OPERATIONS, null, msgs);
      if (newFThenOperations != null)
        msgs = ((InternalEObject)newFThenOperations).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - PogLPackage.FTHEN__FTHEN_OPERATIONS, null, msgs);
      msgs = basicSetFThenOperations(newFThenOperations, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, PogLPackage.FTHEN__FTHEN_OPERATIONS, newFThenOperations, newFThenOperations));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case PogLPackage.FTHEN__OPERATIONTRUE:
        return basicSetOperationtrue(null, msgs);
      case PogLPackage.FTHEN__FTHEN_OPERATIONS:
        return basicSetFThenOperations(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case PogLPackage.FTHEN__OPERATIONTRUE:
        return getOperationtrue();
      case PogLPackage.FTHEN__FTHEN_OPERATIONS:
        return getFThenOperations();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case PogLPackage.FTHEN__OPERATIONTRUE:
        setOperationtrue((Operations)newValue);
        return;
      case PogLPackage.FTHEN__FTHEN_OPERATIONS:
        setFThenOperations((FThenOperations)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case PogLPackage.FTHEN__OPERATIONTRUE:
        setOperationtrue((Operations)null);
        return;
      case PogLPackage.FTHEN__FTHEN_OPERATIONS:
        setFThenOperations((FThenOperations)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case PogLPackage.FTHEN__OPERATIONTRUE:
        return operationtrue != null;
      case PogLPackage.FTHEN__FTHEN_OPERATIONS:
        return fThenOperations != null;
    }
    return super.eIsSet(featureID);
  }

} //FthenImpl
