/**
 * generated by Xtext 2.30.0
 */
package org.xtext.poglanguage.pogl.pogL.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.poglanguage.pogl.pogL.FThenOperations;
import org.xtext.poglanguage.pogl.pogL.Operations;
import org.xtext.poglanguage.pogl.pogL.PogLPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>FThen Operations</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.poglanguage.pogl.pogL.impl.FThenOperationsImpl#getOperationfalse <em>Operationfalse</em>}</li>
 * </ul>
 *
 * @generated
 */
public class FThenOperationsImpl extends MinimalEObjectImpl.Container implements FThenOperations
{
  /**
   * The cached value of the '{@link #getOperationfalse() <em>Operationfalse</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getOperationfalse()
   * @generated
   * @ordered
   */
  protected Operations operationfalse;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected FThenOperationsImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return PogLPackage.Literals.FTHEN_OPERATIONS;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Operations getOperationfalse()
  {
    return operationfalse;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetOperationfalse(Operations newOperationfalse, NotificationChain msgs)
  {
    Operations oldOperationfalse = operationfalse;
    operationfalse = newOperationfalse;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, PogLPackage.FTHEN_OPERATIONS__OPERATIONFALSE, oldOperationfalse, newOperationfalse);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setOperationfalse(Operations newOperationfalse)
  {
    if (newOperationfalse != operationfalse)
    {
      NotificationChain msgs = null;
      if (operationfalse != null)
        msgs = ((InternalEObject)operationfalse).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - PogLPackage.FTHEN_OPERATIONS__OPERATIONFALSE, null, msgs);
      if (newOperationfalse != null)
        msgs = ((InternalEObject)newOperationfalse).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - PogLPackage.FTHEN_OPERATIONS__OPERATIONFALSE, null, msgs);
      msgs = basicSetOperationfalse(newOperationfalse, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, PogLPackage.FTHEN_OPERATIONS__OPERATIONFALSE, newOperationfalse, newOperationfalse));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case PogLPackage.FTHEN_OPERATIONS__OPERATIONFALSE:
        return basicSetOperationfalse(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case PogLPackage.FTHEN_OPERATIONS__OPERATIONFALSE:
        return getOperationfalse();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case PogLPackage.FTHEN_OPERATIONS__OPERATIONFALSE:
        setOperationfalse((Operations)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case PogLPackage.FTHEN_OPERATIONS__OPERATIONFALSE:
        setOperationfalse((Operations)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case PogLPackage.FTHEN_OPERATIONS__OPERATIONFALSE:
        return operationfalse != null;
    }
    return super.eIsSet(featureID);
  }

} //FThenOperationsImpl
