/**
 * generated by Xtext 2.30.0
 */
package org.xtext.poglanguage.pogl.pogL.impl;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.xtext.poglanguage.pogl.pogL.Fstate;
import org.xtext.poglanguage.pogl.pogL.Goto;
import org.xtext.poglanguage.pogl.pogL.PogLPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Goto</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.poglanguage.pogl.pogL.impl.GotoImpl#getState_name <em>State name</em>}</li>
 * </ul>
 *
 * @generated
 */
public class GotoImpl extends OperationImpl implements Goto
{
  /**
   * The cached value of the '{@link #getState_name() <em>State name</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getState_name()
   * @generated
   * @ordered
   */
  protected Fstate state_name;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected GotoImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return PogLPackage.Literals.GOTO;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Fstate getState_name()
  {
    if (state_name != null && state_name.eIsProxy())
    {
      InternalEObject oldState_name = (InternalEObject)state_name;
      state_name = (Fstate)eResolveProxy(oldState_name);
      if (state_name != oldState_name)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, PogLPackage.GOTO__STATE_NAME, oldState_name, state_name));
      }
    }
    return state_name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Fstate basicGetState_name()
  {
    return state_name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setState_name(Fstate newState_name)
  {
    Fstate oldState_name = state_name;
    state_name = newState_name;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, PogLPackage.GOTO__STATE_NAME, oldState_name, state_name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case PogLPackage.GOTO__STATE_NAME:
        if (resolve) return getState_name();
        return basicGetState_name();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case PogLPackage.GOTO__STATE_NAME:
        setState_name((Fstate)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case PogLPackage.GOTO__STATE_NAME:
        setState_name((Fstate)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case PogLPackage.GOTO__STATE_NAME:
        return state_name != null;
    }
    return super.eIsSet(featureID);
  }

} //GotoImpl
