/**
 * generated by Xtext 2.30.0
 */
package org.xtext.poglanguage.pogl.pogL.impl;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;

import org.eclipse.emf.ecore.impl.EFactoryImpl;

import org.eclipse.emf.ecore.plugin.EcorePlugin;

import org.xtext.poglanguage.pogl.pogL.*;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model <b>Factory</b>.
 * <!-- end-user-doc -->
 * @generated
 */
public class PogLFactoryImpl extends EFactoryImpl implements PogLFactory
{
  /**
   * Creates the default factory implementation.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static PogLFactory init()
  {
    try
    {
      PogLFactory thePogLFactory = (PogLFactory)EPackage.Registry.INSTANCE.getEFactory(PogLPackage.eNS_URI);
      if (thePogLFactory != null)
      {
        return thePogLFactory;
      }
    }
    catch (Exception exception)
    {
      EcorePlugin.INSTANCE.log(exception);
    }
    return new PogLFactoryImpl();
  }

  /**
   * Creates an instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public PogLFactoryImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EObject create(EClass eClass)
  {
    switch (eClass.getClassifierID())
    {
      case PogLPackage.PROGRAM: return createProgram();
      case PogLPackage.MODEL: return createModel();
      case PogLPackage.STATE: return createState();
      case PogLPackage.FSTATE: return createFstate();
      case PogLPackage.FSTATE_NAME: return createFstate_name();
      case PogLPackage.ITEM: return createItem();
      case PogLPackage.FITEM: return createFitem();
      case PogLPackage.FITEM_NAME: return createFitem_name();
      case PogLPackage.GOTO: return createGoto();
      case PogLPackage.SHOW: return createShow();
      case PogLPackage.OPERATION: return createOperation();
      case PogLPackage.OPERATIONS: return createOperations();
      case PogLPackage.FOPERATIONS: return createFOperations();
      case PogLPackage.CHECK: return createCheck();
      case PogLPackage.FCHECK: return createFCheck();
      case PogLPackage.FCHECK_ITEM: return createFCheck_item();
      case PogLPackage.FCOMPARISON_OPERATORS: return createFComparison_Operators();
      case PogLPackage.FINT: return createFINT();
      case PogLPackage.FTHEN: return createFthen();
      case PogLPackage.FTHEN_OPERATIONS: return createFThenOperations();
      case PogLPackage.ACTION: return createAction();
      default:
        throw new IllegalArgumentException("The class '" + eClass.getName() + "' is not a valid classifier");
    }
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Program createProgram()
  {
    ProgramImpl program = new ProgramImpl();
    return program;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Model createModel()
  {
    ModelImpl model = new ModelImpl();
    return model;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public State createState()
  {
    StateImpl state = new StateImpl();
    return state;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Fstate createFstate()
  {
    FstateImpl fstate = new FstateImpl();
    return fstate;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Fstate_name createFstate_name()
  {
    Fstate_nameImpl fstate_name = new Fstate_nameImpl();
    return fstate_name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Item createItem()
  {
    ItemImpl item = new ItemImpl();
    return item;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Fitem createFitem()
  {
    FitemImpl fitem = new FitemImpl();
    return fitem;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Fitem_name createFitem_name()
  {
    Fitem_nameImpl fitem_name = new Fitem_nameImpl();
    return fitem_name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Goto createGoto()
  {
    GotoImpl goto_ = new GotoImpl();
    return goto_;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Show createShow()
  {
    ShowImpl show = new ShowImpl();
    return show;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Operation createOperation()
  {
    OperationImpl operation = new OperationImpl();
    return operation;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Operations createOperations()
  {
    OperationsImpl operations = new OperationsImpl();
    return operations;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public FOperations createFOperations()
  {
    FOperationsImpl fOperations = new FOperationsImpl();
    return fOperations;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Check createCheck()
  {
    CheckImpl check = new CheckImpl();
    return check;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public FCheck createFCheck()
  {
    FCheckImpl fCheck = new FCheckImpl();
    return fCheck;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public FCheck_item createFCheck_item()
  {
    FCheck_itemImpl fCheck_item = new FCheck_itemImpl();
    return fCheck_item;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public FComparison_Operators createFComparison_Operators()
  {
    FComparison_OperatorsImpl fComparison_Operators = new FComparison_OperatorsImpl();
    return fComparison_Operators;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public FINT createFINT()
  {
    FINTImpl fint = new FINTImpl();
    return fint;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Fthen createFthen()
  {
    FthenImpl fthen = new FthenImpl();
    return fthen;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public FThenOperations createFThenOperations()
  {
    FThenOperationsImpl fThenOperations = new FThenOperationsImpl();
    return fThenOperations;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Action createAction()
  {
    ActionImpl action = new ActionImpl();
    return action;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public PogLPackage getPogLPackage()
  {
    return (PogLPackage)getEPackage();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @deprecated
   * @generated
   */
  @Deprecated
  public static PogLPackage getPackage()
  {
    return PogLPackage.eINSTANCE;
  }

} //PogLFactoryImpl
