/**
 * generated by Xtext 2.30.0
 */
package org.xtext.poglanguage.pogl.pogL.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.poglanguage.pogl.pogL.PogLPackage;
import org.xtext.poglanguage.pogl.pogL.State;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>State</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class StateImpl extends OperationImpl implements State
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected StateImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return PogLPackage.Literals.STATE;
  }

} //StateImpl
